#!/usr/bin/env bash
# Clean the CURRENT commit (HEAD) into a Conventional Commit.
# Requirements: bash, git, curl, jq
# Env:
#   GEMINI_API_KEY (required)
#   GEMINI_MODEL   (optional, default: gemini-2.5-flash)
#   BRANCH_ISSUES  (optional, e.g. "742 9012" from branch name)

set -euo pipefail

# 0) Skip merge commits (keep their messages)
PARENTS="$(git rev-list --parents -n 1 HEAD)"
if [ "$(wc -w <<<"$PARENTS")" -gt 2 ]; then
  exit 0
fi

# 1) Metadata (preserve authorship & times)
AN="$(git show -s --format='%an' HEAD)"
AE="$(git show -s --format='%ae' HEAD)"
AD="$(git show -s --format='%ad' --date=iso-strict HEAD)"
CN="$(git show -s --format='%cn' HEAD)"
CE="$(git show -s --format='%ce' HEAD)"
CD="$(git show -s --format='%cd' --date=iso-strict HEAD)"
ORIG_MSG="$(git log -1 --pretty=%B HEAD)"

# 2) Diff vs parent (or empty tree for root)
if git rev-parse HEAD^ >/dev/null 2>&1; then
  DIFF="$(git diff --no-color -U0 HEAD^ HEAD || true)"
  STATS="$(git diff --numstat HEAD^ HEAD || true)"
else
  EMPTY="4b825dc642cb6eb9a060e54bf8d69288fbee4904"
  DIFF="$(git diff --no-color -U0 $EMPTY HEAD || true)"
  STATS="$(git diff --numstat $EMPTY HEAD || true)"
fi
[ -z "$DIFF" ] && exit 0

# 3) Decide 2–4 paragraphs from change size
LINES=$(awk '{a+=$1;b+=$2} END{print (a+b)+0}' <<<"$STATS")
FILES=$(wc -l <<<"$STATS" | tr -d ' ')
PARAS=2
if [ "${LINES:-0}" -ge 120 ] || [ "${FILES:-0}" -ge 5 ]; then PARAS=3; fi
if [ "${LINES:-0}" -ge 400 ] || [ "${FILES:-0}" -ge 12 ]; then PARAS=4; fi

# 4) Preserve standard trailers (legal/links only)
TRAILERS="$(grep -Ei '^(Signed-off-by|Co-authored-by|Fix(e[sd])?|Close[sd]?|Resolve[sd]?|Ref(s)?|Reference(s)?):' <<<"$ORIG_MSG" || true)"

# 5) Ask Gemini for a Conventional Commit
: "${GEMINI_MODEL:=gemini-2.5-flash}"
if [ -z "${GEMINI_API_KEY:-}" ]; then
  echo "GEMINI_API_KEY is required" >&2
  exit 1
fi

read -r -d '' PROMPT <<EOP
You are a commit message generator. Produce a Conventional Commit with:
- SUBJECT: "type(scope): subject" — <=72 chars, imperative, no trailing period.
- BODY: exactly ${PARAS} paragraph(s), 1–3 sentences each. Plain sentences.
  Put ONE blank line between paragraphs. No lists/headings/emojis/code fences.
- Allowed types: feat, fix, refactor, perf, docs, style, test, build, ci, chore, revert.
- Add "!" after type if the diff clearly indicates a BREAKING CHANGE.

Return ONLY the commit message (subject line, blank line, body). No extra text.

Unified diff:
$DIFF
EOP

JSON=$(jq -cn --arg t "$PROMPT" '{contents:[{parts:[{text:$t}]}]}')
RESP="$(curl -sS -X POST -H "Content-Type: application/json" \
  "https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${GEMINI_API_KEY}" \
  -d "$JSON" || true)"
NEW="$(jq -r '.candidates[0].content.parts[0].text // empty' <<<"$RESP" | tr -d $'\r')"

# Fallback if model didn’t return text
if [ -z "${NEW:-}" ]; then
  FILELIST="$(git show --name-only --pretty=format: HEAD | tail -n +2 | sed 's#.*/##' | tr '\n' ' ' | cut -c1-60)"
  TYPE="chore"
  if git show --name-only --pretty=format: HEAD | grep -E '\.(ts|js|tsx|jsx|dart|go|py|rb|java|kt|swift|cs|php)$' >/dev/null; then TYPE="feat"; fi
  NEW="${TYPE}: auto-relabel ${FILELIST:-changes}

Maintains Conventional Commits formatting automatically.

Generated by fallback when AI is temporarily unavailable."
fi

# 6) Promote real GitHub issue IDs into a Reference footer (non-closing)
extract_ids() { grep -Eo '([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+)?#[0-9]+' | sed 's/.*#//'; }

listed_ids="$(printf '%s\n' "$TRAILERS" | extract_ids | sort -u)"
found_ids_msg="$(printf '%s\n' "$ORIG_MSG" | grep -Eo '#[0-9]+' | tr -d '#' | sort -u)"
found_ids_branch="$(tr ' ' '\n' <<<"${BRANCH_ISSUES:-}" | grep -E '^[0-9]+$' | sort -u)"
ids_union="$(printf '%s\n%s\n' "$found_ids_msg" "$found_ids_branch" | sort -u)"
ids_to_add="$(comm -23 <(printf '%s\n' $ids_union | sort -u) <(printf '%s\n' $listed_ids | sort -u))"

if [ -n "$ids_to_add" ]; then
  refs_line="$(printf '#%s, ' $ids_to_add | sed 's/, $//')"
  TRAILERS="${TRAILERS:+$TRAILERS$'\n'}Reference: ${refs_line}"
fi

# 7) Attach trailers and recreate the commit
if [ -n "${TRAILERS:-}" ]; then
  NEW="${NEW}

${TRAILERS}"
fi

# Recreate the commit with original identity + timestamps
if git rev-parse HEAD^ >/dev/null 2>&1; then
  git reset --soft HEAD^
else
  git reset
  git add -A
fi

GIT_AUTHOR_NAME="$AN" GIT_AUTHOR_EMAIL="$AE" GIT_AUTHOR_DATE="$AD" \
GIT_COMMITTER_NAME="$CN" GIT_COMMITTER_EMAIL="$CE" GIT_COMMITTER_DATE="$CD" \
  git commit -F- --no-verify <<<"$NEW"
