name: "🛡️ Vulnerability Report"
description: "PRIVATE repos only: report suspected vulnerabilities here. For PUBLIC repos, do not open an issue—use SECURITY.md for private reporting."
title: "🛡️ Security: <Area/Component> — <Concise Summary>"
labels:
  - "priority: To be determined (TBD)"
  - "status: Needs triage"
  - "type: Security"
assignees:
  - tannergolden
body:
  - type: markdown
    attributes:
      value: |
        > **Important**
        > - **PRIVATE repositories only.** If this is a **PUBLIC** repository, stop and follow **SECURITY.md** (Security → Report a vulnerability) or email the security team.
        > - Do **not** include secrets or **Personally Identifiable Information (PII)**.
        > - Follow good-faith testing rules (no service disruption, no data exfiltration, use test accounts).

        ## 📌 What this template is for (and not for)

        **Use this template for security vulnerabilities, for example:**
        - Authn/Authz bypass (login bypass, privilege escalation)
        - Sensitive data exposure (IDOR, missing access controls)
        - Injection (SQL/NoSQL/LDAP), XSS, CSRF
        - SSRF, path traversal, RCE
        - Insecure configuration or secrets leakage
        - Broken crypto/transport (weak algorithms, missing TLS)
        - Supply chain risks (malicious deps, unsafe script loads)

        **Do not use this template for (use these instead):**
        - 🐛 Bug Report
        • 📝 Feedback Report
        • 📚 Documentation Report
        • ♿ Accessibility Report
        • ✨ Feature Request
        • 🚀 Performance Report

  - type: textarea
    id: summary
    attributes:
      label: "🔎 Summary"
      description: "Clear description of the suspected vulnerability and its impact."
      placeholder: |
        What is affected, and what can an attacker achieve? (e.g., read arbitrary data, escalate privileges)
    validations:
      required: true

  - type: textarea
    id: preconditions
    attributes:
      label: "✅ Preconditions / context"
      description: "Anything needed before exploitation works."
      placeholder: |
        - Authentication/role required: …
        - Special configuration/feature flags: …
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "🧪 Steps to reproduce"
      description: "Numbered, minimal steps to trigger the issue."
      placeholder: |
        1) …
        2) …
        3) …
        **Expected result:** …
        **Actual result:** …
    validations:
      required: true

  - type: textarea
    id: poc
    attributes:
      label: "💣 Proof of Concept (PoC)"
      description: "Requests, payloads, or minimal code that demonstrates impact. Redact tokens or sensitive data."
      placeholder: |
        # Example request/command/output
        # curl https://api.example.com/…
        # POST /endpoint with payload {…}
        # Observed response: …
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: "📈 Impact assessment"
      description: "Practical risk and blast radius."
      placeholder: |
        - Data exposure/modification potential: …
        - Lateral movement/account takeover implications: …
        - Reliability/ease of exploitation: …
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "🧮 Severity (self-assessment)"
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: input
    id: cvss
    attributes:
      label: "📊 CVSS vector (optional)"
      placeholder: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"

  - type: textarea
    id: affected_components
    attributes:
      label: "🧰 Affected components / versions"
      description: "What repos/packages, versions/commits, and environments are impacted."
      placeholder: |
        - Repository/package: …
        - Version(s) or commit(s): …
        - Environments: Production / Preview / Development
    validations:
      required: true

  - type: textarea
    id: environment_details
    attributes:
      label: "🖥️ Environment details"
      description: "OS/Browser/App version, build number/commit hash, relevant config flags."
      placeholder: |
        - OS/Browser/App version: …
        - Build number / Commit hash: …
        - Config flags: …

  - type: textarea
    id: logs
    attributes:
      label: "🧩 Logs / artifacts (redacted)"
      description: "Attach only what is necessary; remove secrets and PII."
      placeholder: |
        Snippets, stack traces, headers, sanitized screenshots.

  - type: textarea
    id: mitigations
    attributes:
      label: "🚧 Mitigations / workarounds (if any)"
      description: "Temporary steps to reduce risk until a fix is shipped."
      placeholder: "Describe immediate mitigations or containment steps."

  - type: textarea
    id: related
    attributes:
      label: "🔁 Related items"
      description: "Linked Issues / PRs / Advisories, if applicable."
      placeholder: "- Issue #…\n- PR #…\n- Advisory: …"

  - type: input
    id: reporter_contact
    attributes:
      label: "👤 Reporter contact"
      description: "Preferred contact (email or handle)."
      placeholder: "name@example.com / @handle"

  - type: checkboxes
    id: reporter_checklist
    attributes:
      label: "✅ Reporter checklist"
      options:
        - label: "This report is for a **PRIVATE repository**."
          required: true
        - label: "I did not include secrets or **Personally Identifiable Information (PII)**."
          required: true
        - label: "I followed good-faith testing rules (no disruption or data exfiltration)."
          required: true
        - label: "I understand coordinated disclosure timelines may apply."
          required: true

  - type: markdown
    attributes:
      value: |
        > **For maintainers:** Convert to a **Draft Security Advisory** if needed and coordinate the fix privately. When ready, publish advisory notes and provide credit (with consent).
